version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://server:3000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/family-network
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

